/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.analysis;

import simpleAdder.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTNum(TNum node);
    void caseTId(TId node);
    void caseTSe(TSe node);
    void caseTEnq(TEnq node);
    void caseTSenao(TSenao node);
    void caseTInteiro(TInteiro node);
    void caseTRetorno(TRetorno node);
    void caseTVazio(TVazio node);
    void caseTAdd(TAdd node);
    void caseTSub(TSub node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTMenor(TMenor node);
    void caseTMaior(TMaior node);
    void caseTMenorIgl(TMenorIgl node);
    void caseTMaiorIgl(TMaiorIgl node);
    void caseTIgl(TIgl node);
    void caseTDif(TDif node);
    void caseTAtr(TAtr node);
    void caseTParEs(TParEs node);
    void caseTParDir(TParDir node);
    void caseTChavesDir(TChavesDir node);
    void caseTChavesEsq(TChavesEsq node);
    void caseTPontoVrg(TPontoVrg node);
    void caseTBranco(TBranco node);
    void caseTComentarioLn(TComentarioLn node);
    void caseTComentarioAninhado(TComentarioAninhado node);
    void caseTFimComentarioAninhado(TFimComentarioAninhado node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
